---
- hosts: local
  tasks:
  - name: Start Apache2
    service: 
      name: apache2
      state: started
  - name: index.html copy
    template: src=helloworld.html dest=/var/www/html/helloworld.html

